name: Publish npm Package

on:
  push:
    branches:
      - main  # Adjust if your default branch is not 'main'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify your Node.js version
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Authenticate npm
      - name: Authenticate npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Run tests (optional)
      - name: Run tests
        run: npm test

      # Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Push changes to GitHub (optional if you're updating files during publish)
      - name: Push changes back to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update from GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
