name: Publish npm Package

on:
  push:
    branches:
      - main  # Adjust if your default branch is not 'main'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify your Node.js version
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Authenticate npm
      - name: Authenticate npm
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Run tests (optional)
      - name: Run tests
        run: npm test

      # Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Configure SSH for GitHub
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Configure Git to use SSH and push changes back to GitHub
      - name: Push changes back to GitHub
        run: |
          git config user.name "muslihabdiker"
          git config user.email "info@muslih.tech"
          git remote set-url origin git@github.com:muslihabdiker/vplusplus.git
          git add .
          git commit -m "Automated update from GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
