name: Publish to npm & Release on GitHub

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write     # needed to push tags and create releases
  packages: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need tags for the idempotency check

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      # Optional build (runs only if a build script exists)
      - name: Build
        shell: bash
        run: |
          if jq -e '.scripts.build' package.json >/dev/null 2>&1; then
            npm run build
          else
            echo "No build script found, skipping."
          fi

      # Tests: succeed even if you have none
      - name: Run tests
        shell: bash
        run: |
          if git ls-files "**/*.test.*" "**/*.spec.*" "**/__tests__/**/*" | grep -q .; then
            npm test --silent -- --passWithNoTests
          else
            echo "No tests found, skipping."
          fi

      # Read package version (fixed: no command-substitution-in-echo issue)
      - name: Read package version
        id: pkg
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Package version: $VERSION"

      # Skip if tag exists (idempotent)
      - name: Check if tag already exists
        id: tagcheck
        shell: bash
        run: |
          TAG="v${{ steps.pkg.outputs.version }}"
          if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "Tag $TAG already exists. Skipping publish & release."
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      # npm auth
      - name: Authenticate to npm
        if: steps.tagcheck.outputs.exists == 'false'
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Optional sanity: show name/version/public access
      - name: Echo pkg info
        if: steps.tagcheck.outputs.exists == 'false'
        shell: bash
        run: |
          echo "name: $(node -p "require('./package.json').name")"
          echo "version: $(node -p "require('./package.json').version")"
          echo "publishConfig: $(node -p "JSON.stringify(require('./package.json').publishConfig || {})")"

      # Publish to npm
      - name: Publish to npm
        if: steps.tagcheck.outputs.exists == 'false'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Add --access public for scoped public packages; harmless for unscoped too.
          # Add --provenance if your repo is public and you want SLSA provenance.
          npm publish --access public

      # Create and push git tag
      - name: Create git tag
        if: steps.tagcheck.outputs.exists == 'false'
        shell: bash
        run: |
          TAG="v${{ steps.pkg.outputs.version }}"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

      # Create GitHub Release
      - name: Create GitHub Release
        if: steps.tagcheck.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pkg.outputs.version }}
          name: v${{ steps.pkg.outputs.version }}
          generate_release_notes: true
